[project]
name = "anomaly-detection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "albumentationsx>=2.0.11",
    "anomalib>=2.1.0",
    "jupyterlab>=4.4.7",
    "pip>=25.2",
]
